server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gameservice
    username: java
    password: javapassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
